// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhaBg_wgMFAXq2FAbjN9hjdQkSCyLjN0o',
    appId: '1:971499215338:web:a373df3a52bf435d023a93',
    messagingSenderId: '971499215338',
    projectId: 'chat-app-9659a',
    authDomain: 'chat-app-9659a.firebaseapp.com',
    storageBucket: 'chat-app-9659a.appspot.com',
    measurementId: 'G-WFPXFLPFCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1suLNQRRL7xgMXE3OifqivmfEpwrgDwQ',
    appId: '1:971499215338:android:e11ecf20fd4b6c91023a93',
    messagingSenderId: '971499215338',
    projectId: 'chat-app-9659a',
    storageBucket: 'chat-app-9659a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTg81YgsSJPEHGyWBNKvUVwnRzlxg67Ps',
    appId: '1:971499215338:ios:dbe34d07cbc1e486023a93',
    messagingSenderId: '971499215338',
    projectId: 'chat-app-9659a',
    storageBucket: 'chat-app-9659a.appspot.com',
    iosBundleId: 'com.example.fullStackChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTg81YgsSJPEHGyWBNKvUVwnRzlxg67Ps',
    appId: '1:971499215338:ios:c0ff4996594beb08023a93',
    messagingSenderId: '971499215338',
    projectId: 'chat-app-9659a',
    storageBucket: 'chat-app-9659a.appspot.com',
    iosBundleId: 'com.example.fullStackChatApp.RunnerTests',
  );
}
